Hw02 task03
julwein/hw pull request #8
Opened 2021-04-22 14:23 UTC by julwein

2021-04-22 19:08 UTC, Cjkjvfnby requested changes

2021-04-22 19:08 UTC, Cjkjvfnby commented on homework_02/task_03.py
> +def combinations(*args: List[Any]) -> List[List]:
Please add tests.

2021-04-22 19:08 UTC, Cjkjvfnby commented on homework_02/task_03.py
> +    for tup in product(*args):
Let's do it in a low-level way, without libs.

2021-05-18 18:51 UTC, Cjkjvfnby approved these changes
Ok.

Bonus task: solve it with the `itertools` module.

2021-05-19 11:05 UTC, julwein commented
> Bonus task: solve it with the `itertools` module.

Done - that was the first solution.

2021-05-19 20:08 UTC, merged